# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "agent_fix"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Lane"]
  s.date = "2013-08-01"
  s.description = "Interact with FIX connections to send, receive, and inspect messages in cucumber"
  s.email = "support@connamara.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "config/fix_agents.rb",
    "features/logon.feature",
    "features/new_order_sequence.feature",
    "features/scope.feature",
    "features/step_definitions/steps.rb",
    "features/support/FIX42.xml",
    "features/support/env.rb",
    "features/test_request.feature",
    "lib/agent_fix.rb",
    "lib/agent_fix/agent.rb",
    "lib/agent_fix/configuration.rb",
    "lib/agent_fix/cucumber.rb",
    "lib/agent_fix/message_cache.rb"
  ]
  s.homepage = "http://github.com/connamara/agent_fix"
  s.licenses = ["Connamara"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Agent framework for FIX messages"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<quickfix>, [">= 0"])
      s.add_runtime_dependency(%q<anticipate>, [">= 0"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0"])
      s.add_runtime_dependency(%q<fix_spec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<quickfix>, [">= 0"])
      s.add_dependency(%q<anticipate>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<fix_spec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<quickfix>, [">= 0"])
    s.add_dependency(%q<anticipate>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<fix_spec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

