# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: agent_fix 0.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "agent_fix"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Lane", "Chris Busbey", "Mike Gatny"]
  s.date = "2015-06-29"
  s.description = "Interact with FIX connections to send, receive, and inspect messages in cucumber"
  s.email = "info@connamara.com"
  s.extra_rdoc_files = ["LICENSE.txt", "README.md"]

  s.files = Dir['lib/**/*',
                'spec/**/*',
                'features/**/*',
                'config/*',
                'vendor/**/*',
                '*.gemspec',
                '*.md',
                'Gemfile',
                'LICENSE.txt',
                'QUICKFIX_LICENSE.txt',
                'VERSION',
                'Rakefile',
                '.travis.yml']

  s.test_files = s.files.grep(%r{^(spec|features)/})

  s.homepage = "http://github.com/connamara/agent_fix"
  s.licenses = ["GPL"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.9"
  s.summary = "Agent framework for FIX messages"

  s.add_runtime_dependency(%q<quickfix-jruby>, ["~> 1.6.0"])
  s.add_runtime_dependency(%q<anticipate>)
  s.add_runtime_dependency(%q<cucumber>, ["~> 1.3"])
  s.add_runtime_dependency(%q<fix_spec>, [">= 1.0.0"])
  s.add_runtime_dependency(%q<rspec>, ["~> 3.0"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
  s.add_development_dependency(%q<rake>, ["~> 10.1"])
end

